// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace CodesCampaigns.Api.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CampaignsManagementFeature : object, global::Xunit.IClassFixture<CampaignsManagementFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Campaigns management", "  As a developer\r\n  I want to have a set of endpoints to manage campaigns", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Campaigns.feature"
#line hidden
        
        public CampaignsManagementFeature(CampaignsManagementFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
  #line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "Id",
                        "Name"});
            table1.AddRow(new string[] {
                        "11111111-1111-1111-1111-111111111111",
                        "Campaign One"});
            table1.AddRow(new string[] {
                        "22222222-2222-2222-2222-222222222222",
                        "Campaign Two"});
#line 6
    await testRunner.GivenAsync("the following campaigns exist:", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Campaigns.feature.ndjson", 24);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get all campaigns")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Get all campaigns")]
        public async global::System.Threading.Tasks.Task GetAllCampaigns()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get all campaigns", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table2.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 12
    await testRunner.WhenAsync("I send a GET request to \"/api/campaigns\" with headers:", ((string)(null)), table2, "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
    await testRunner.AndAsync("the response should match JSON:", "[\r\n  { \"id\": \"11111111-1111-1111-1111-111111111111\", \"name\": \"Campaign One\" },\r\n " +
                        " { \"id\": \"22222222-2222-2222-2222-222222222222\", \"name\": \"Campaign Two\" }\r\n]", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Unauthorized access is denied when no API key is provided for retrieving all camp" +
            "aigns")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Unauthorized access is denied when no API key is provided for retrieving all camp" +
            "aigns")]
        public async global::System.Threading.Tasks.Task UnauthorizedAccessIsDeniedWhenNoAPIKeyIsProvidedForRetrievingAllCampaigns()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Unauthorized access is denied when no API key is provided for retrieving all camp" +
                    "aigns", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.WhenAsync("I send a GET request to \"/api/campaigns\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("the response status code should be 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Access is forbidden when an invalid API key is provided for retrieving all campai" +
            "gns")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Access is forbidden when an invalid API key is provided for retrieving all campai" +
            "gns")]
        public async global::System.Threading.Tasks.Task AccessIsForbiddenWhenAnInvalidAPIKeyIsProvidedForRetrievingAllCampaigns()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Access is forbidden when an invalid API key is provided for retrieving all campai" +
                    "gns", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table3.AddRow(new string[] {
                            "X-API-KEY",
                            "invalid-key"});
#line 29
    await testRunner.WhenAsync("I send a GET request to \"/api/campaigns\" with headers:", ((string)(null)), table3, "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get single campaign by ID")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Get single campaign by ID")]
        public async global::System.Threading.Tasks.Task GetSingleCampaignByID()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get single campaign by ID", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table4.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 35
    await testRunner.WhenAsync("I send a GET request to \"/api/campaigns/11111111-1111-1111-1111-111111111111\" wit" +
                        "h headers:", ((string)(null)), table4, "When ");
#line hidden
#line 38
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
    await testRunner.AndAsync("the response should match JSON:", "{ \"id\": \"11111111-1111-1111-1111-111111111111\", \"name\": \"Campaign One\" }", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get single campaign by unexisting ID")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Get single campaign by unexisting ID")]
        public async global::System.Threading.Tasks.Task GetSingleCampaignByUnexistingID()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get single campaign by unexisting ID", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table5.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 45
    await testRunner.WhenAsync("I send a GET request to \"/api/campaigns/33333333-3333-3333-3333-333333333333\" wit" +
                        "h headers:", ((string)(null)), table5, "When ");
#line hidden
#line 48
    await testRunner.ThenAsync("the response status code should be 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Unauthorized access is denied when no API key is provided for retrieving single c" +
            "ampaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Unauthorized access is denied when no API key is provided for retrieving single c" +
            "ampaign")]
        public async global::System.Threading.Tasks.Task UnauthorizedAccessIsDeniedWhenNoAPIKeyIsProvidedForRetrievingSingleCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Unauthorized access is denied when no API key is provided for retrieving single c" +
                    "ampaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 50
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 51
    await testRunner.WhenAsync("I send a GET request to \"/api/campaigns/11111111-1111-1111-1111-111111111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("the response status code should be 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Access is forbidden when an invalid API key is provided for retrieving single cam" +
            "paign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Access is forbidden when an invalid API key is provided for retrieving single cam" +
            "paign")]
        public async global::System.Threading.Tasks.Task AccessIsForbiddenWhenAnInvalidAPIKeyIsProvidedForRetrievingSingleCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Access is forbidden when an invalid API key is provided for retrieving single cam" +
                    "paign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table6.AddRow(new string[] {
                            "X-API-KEY",
                            "invalid-key"});
#line 55
    await testRunner.WhenAsync("I send a GET request to \"/api/campaigns/11111111-1111-1111-1111-111111111111\" wit" +
                        "h headers:", ((string)(null)), table6, "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create a new campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Create a new campaign")]
        public async global::System.Threading.Tasks.Task CreateANewCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create a new campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table7.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 61
    await testRunner.WhenAsync("I set the following headers:", ((string)(null)), table7, "When ");
#line hidden
#line 64
    await testRunner.AndAsync("I send a POST request to \"/api/campaigns\" with body:", "{\r\n  \"name\": \"New Campaign\"\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.ThenAsync("the response status code should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table8.AddRow(new string[] {
                            "Campaign One"});
                table8.AddRow(new string[] {
                            "Campaign Two"});
                table8.AddRow(new string[] {
                            "New Campaign"});
#line 71
    await testRunner.ThenAsync("there are following Campaigns in the database", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Validation for creating campaing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Validation for creating campaing")]
        public async global::System.Threading.Tasks.Task ValidationForCreatingCampaing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validation for creating campaing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 77
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table9.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 78
    await testRunner.WhenAsync("I set the following headers:", ((string)(null)), table9, "When ");
#line hidden
#line 81
    await testRunner.AndAsync("I send a POST request to \"/api/campaigns\" with body:", "{\r\n  \"name\": \"\"\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Unauthorized access is denied when no API key is provided for creating campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Unauthorized access is denied when no API key is provided for creating campaign")]
        public async global::System.Threading.Tasks.Task UnauthorizedAccessIsDeniedWhenNoAPIKeyIsProvidedForCreatingCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Unauthorized access is denied when no API key is provided for creating campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 89
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 90
    await testRunner.WhenAsync("I send a POST request to \"/api/campaigns\" with body:", "{\r\n  \"name\": \"new\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
    await testRunner.ThenAsync("the response status code should be 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Access is forbidden when an invalid API key is provided for creating campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Access is forbidden when an invalid API key is provided for creating campaign")]
        public async global::System.Threading.Tasks.Task AccessIsForbiddenWhenAnInvalidAPIKeyIsProvidedForCreatingCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Access is forbidden when an invalid API key is provided for creating campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 98
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table10.AddRow(new string[] {
                            "X-API-KEY",
                            "invalid-key"});
#line 99
    await testRunner.WhenAsync("I set the following headers:", ((string)(null)), table10, "When ");
#line hidden
#line 102
    await testRunner.WhenAsync("I send a POST request to \"/api/campaigns\" with body:", "{\r\n  \"name\": \"new\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 108
    await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update a campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Update a campaign")]
        public async global::System.Threading.Tasks.Task UpdateACampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update a campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 110
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table11.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 111
    await testRunner.WhenAsync("I set the following headers:", ((string)(null)), table11, "When ");
#line hidden
#line 114
    await testRunner.AndAsync("I send a PUT request to \"/api/campaigns/11111111-1111-1111-1111-111111111111\" wit" +
                        "h body:", "{\r\n  \"name\": \"Updated campaign one\"\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
    await testRunner.ThenAsync("the response status code should be 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table12.AddRow(new string[] {
                            "Updated campaign one"});
                table12.AddRow(new string[] {
                            "Campaign Two"});
#line 121
    await testRunner.ThenAsync("there are following Campaigns in the database", ((string)(null)), table12, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Validation for updating campaing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Validation for updating campaing")]
        public async global::System.Threading.Tasks.Task ValidationForUpdatingCampaing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validation for updating campaing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 126
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table13.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 127
    await testRunner.WhenAsync("I set the following headers:", ((string)(null)), table13, "When ");
#line hidden
#line 130
    await testRunner.AndAsync("I send a PUT request to \"/api/campaigns/11111111-1111-1111-1111-111111111111\" wit" +
                        "h body:", "{\r\n  \"name\": \"\"\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
    await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update a not existing campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Update a not existing campaign")]
        public async global::System.Threading.Tasks.Task UpdateANotExistingCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update a not existing campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 138
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table14.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 139
    await testRunner.WhenAsync("I set the following headers:", ((string)(null)), table14, "When ");
#line hidden
#line 142
    await testRunner.AndAsync("I send a PUT request to \"/api/campaigns/33333333-3333-3333-3333-333333333333\" wit" +
                        "h body:", "{\r\n  \"name\": \"Updated campaign\"\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 148
    await testRunner.ThenAsync("the response status code should be 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Unauthorized access is denied when no API key is provided for updating campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Unauthorized access is denied when no API key is provided for updating campaign")]
        public async global::System.Threading.Tasks.Task UnauthorizedAccessIsDeniedWhenNoAPIKeyIsProvidedForUpdatingCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Unauthorized access is denied when no API key is provided for updating campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 150
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 151
    await testRunner.WhenAsync("I send a PUT request to \"/api/campaigns/11111111-1111-1111-1111-111111111111\" wit" +
                        "h body:", "{\r\n  \"name\": \"new\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 157
    await testRunner.ThenAsync("the response status code should be 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Access is forbidden when an invalid API key is provided for updating campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Access is forbidden when an invalid API key is provided for updating campaign")]
        public async global::System.Threading.Tasks.Task AccessIsForbiddenWhenAnInvalidAPIKeyIsProvidedForUpdatingCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Access is forbidden when an invalid API key is provided for updating campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 159
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table15.AddRow(new string[] {
                            "X-API-KEY",
                            "invalid-key"});
#line 160
    await testRunner.WhenAsync("I set the following headers:", ((string)(null)), table15, "When ");
#line hidden
#line 163
    await testRunner.WhenAsync("I send a PUT request to \"/api/campaigns/11111111-1111-1111-1111-111111111111\" wit" +
                        "h body:", "{\r\n  \"name\": \"new\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 169
    await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Delete a campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Delete a campaign")]
        public async global::System.Threading.Tasks.Task DeleteACampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete a campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 171
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table16.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 172
    await testRunner.WhenAsync("I send a DELETE request to \"/api/campaigns/11111111-1111-1111-1111-111111111111\" " +
                        "with headers:", ((string)(null)), table16, "When ");
#line hidden
#line 175
    await testRunner.ThenAsync("the response status code should be 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table17.AddRow(new string[] {
                            "Campaign Two"});
#line 176
    await testRunner.ThenAsync("there are following Campaigns in the database", ((string)(null)), table17, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Delete a not existing campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Delete a not existing campaign")]
        public async global::System.Threading.Tasks.Task DeleteANotExistingCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete a not existing campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 180
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table18.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 181
    await testRunner.WhenAsync("I send a DELETE request to \"/api/campaigns/33333333-3333-3333-3333-333333333333\" " +
                        "with headers:", ((string)(null)), table18, "When ");
#line hidden
#line 184
    await testRunner.ThenAsync("the response status code should be 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Unauthorized access is denied when no API key is provided for deleting campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Unauthorized access is denied when no API key is provided for deleting campaign")]
        public async global::System.Threading.Tasks.Task UnauthorizedAccessIsDeniedWhenNoAPIKeyIsProvidedForDeletingCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Unauthorized access is denied when no API key is provided for deleting campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 186
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 187
    await testRunner.WhenAsync("I send a DELETE request to \"/api/campaigns/11111111-1111-1111-1111-111111111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 188
    await testRunner.ThenAsync("the response status code should be 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Access is forbidden when an invalid API key is provided for deleting campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Access is forbidden when an invalid API key is provided for deleting campaign")]
        public async global::System.Threading.Tasks.Task AccessIsForbiddenWhenAnInvalidAPIKeyIsProvidedForDeletingCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Access is forbidden when an invalid API key is provided for deleting campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 190
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table19.AddRow(new string[] {
                            "X-API-KEY",
                            "invalid-key"});
#line 191
    await testRunner.WhenAsync("I send a DELETE request to \"/api/campaigns/11111111-1111-1111-1111-111111111111\" " +
                        "with headers:", ((string)(null)), table19, "When ");
#line hidden
#line 194
    await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create codes in campaign")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Create codes in campaign")]
        public async global::System.Threading.Tasks.Task CreateCodesInCampaign()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create codes in campaign", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 196
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table20.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 197
    await testRunner.WhenAsync("I set the following headers:", ((string)(null)), table20, "When ");
#line hidden
#line 200
    await testRunner.AndAsync("I send a POST request to \"/api/campaigns/11111111-1111-1111-1111-111111111111/cod" +
                        "es\" with body:", "{\r\n  \"count\": 10,\r\n  \"value\": 20,\r\n  \"currency\": \"PLN\"\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 208
    await testRunner.AndAsync("I wait for the jobs to complete", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 209
    await testRunner.ThenAsync("the response status code should be 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 210
    await testRunner.AndAsync("there are 10 TopUps elements in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get campaign codes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Campaigns management")]
        [global::Xunit.TraitAttribute("Description", "Get campaign codes")]
        public async global::System.Threading.Tasks.Task GetCampaignCodes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get campaign codes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 212
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Code",
                            "CampaignId",
                            "Amount",
                            "Currency"});
                table21.AddRow(new string[] {
                            "11111111-1111-1111-1111-111111111111",
                            "22222222-2222-2222-2222-222222222222",
                            "100",
                            "USD"});
                table21.AddRow(new string[] {
                            "22222222-2222-2222-2222-222222222222",
                            "22222222-2222-2222-2222-222222222222",
                            "200",
                            "PLN"});
#line 213
    await testRunner.GivenAsync("the following topups exist:", ((string)(null)), table21, "Given ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "Key",
                            "Value"});
                table22.AddRow(new string[] {
                            "X-API-KEY",
                            "my-super-secret-key"});
#line 217
    await testRunner.WhenAsync("I send a GET request to \"/api/campaigns/22222222-2222-2222-2222-222222222222/code" +
                        "s\" with headers:", ((string)(null)), table22, "When ");
#line hidden
#line 220
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 221
    await testRunner.AndAsync("the response should match JSON:", @"[
  { ""code"": ""11111111-1111-1111-1111-111111111111"", ""amount"": 100, ""currency"": ""USD"", ""campaignId"": ""22222222-2222-2222-2222-222222222222"" },
  { ""code"": ""22222222-2222-2222-2222-222222222222"", ""amount"": 200, ""currency"": ""PLN"", ""campaignId"": ""22222222-2222-2222-2222-222222222222"" }
]", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CampaignsManagementFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CampaignsManagementFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
